import type { DomainMode, DomainModeConfig } from "./types.js";
import { DOMAIN_MODE_VALUES } from "./types.js";

const DOMAIN_MODES: Record<DomainMode, DomainModeConfig> = {
  "product-visual": {
    id: "product-visual",
    name: "Product Visual",
    description: "Professional product photography with clean lighting and detailed textures",
    icon: "📦",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "4:3",
    stylePrefix: "Professional product photography, studio lighting, sharp focus, detailed textures, clean background, commercial quality, ",
    styleSuffix: ", 8K detail, photorealistic, soft shadows",
    visualTraits: ["studio lighting", "sharp focus", "clean background", "photorealistic", "detailed texture"],
  },
  illustration: {
    id: "illustration",
    name: "Illustration",
    description: "Artistic illustrations in various styles",
    icon: "🎨",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "1:1",
    stylePrefix: "Digital illustration, artistic style, vibrant colors, ",
    styleSuffix: ", high detail, professional illustration",
    visualTraits: ["artistic", "vibrant colors", "digital art", "creative", "expressive"],
  },
  "pixel-art": {
    id: "pixel-art",
    name: "Pixel Art",
    description: "Retro pixel art for games and nostalgic designs",
    icon: "🟦",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "1K",
    defaultAspectRatio: "1:1",
    stylePrefix: "Pixel art style, retro game graphics, 8-bit, low resolution, blocky pixels, ",
    styleSuffix: ", pixel perfect, game sprite style, retro",
    visualTraits: ["pixel art", "retro", "8-bit", "blocky", "game style"],
  },
  "ui-design": {
    id: "ui-design",
    name: "UI Design",
    description: "User interface mockups and app screenshots",
    icon: "🖥",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "1K",
    defaultAspectRatio: "16:9",
    stylePrefix: "UI design, clean interface, modern design system, flat design, ",
    styleSuffix: ", app screenshot, professional UI",
    visualTraits: ["clean", "modern", "flat design", "interface", "minimal"],
  },
  photography: {
    id: "photography",
    name: "Photography",
    description: "Realistic photography with natural lighting and composition",
    icon: "📷",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Photorealistic, DSLR photography, natural lighting, ",
    styleSuffix: ", shallow depth of field, 35mm film grain, professional photography",
    visualTraits: ["photorealistic", "natural lighting", "DSLR", "depth of field", "film"],
  },
  "logo-design": {
    id: "logo-design",
    name: "Logo Design",
    description: "Clean logo designs for brands and companies",
    icon: "🔤",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "1:1",
    stylePrefix: "Logo design, minimalist, vector style, clean lines, iconic, ",
    styleSuffix: ", professional logo, scalable vector design, brand identity, text under 25 characters",
    visualTraits: ["minimalist", "vector style", "clean lines", "iconic", "professional"],
  },
  "3d-render": {
    id: "3d-render",
    name: "3D Render",
    description: "3D rendered scenes with realistic materials and lighting",
    icon: "🔮",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "3D render, cinematic lighting, ray tracing, PBR materials, ",
    styleSuffix: ", octane render, unreal engine 5, hyperrealistic, subsurface scattering",
    visualTraits: ["3D render", "cinematic lighting", "ray tracing", "PBR", "hyperrealistic"],
  },
  "character-design": {
    id: "character-design",
    name: "Character Design",
    description: "Character concept art for games, animation, and media",
    icon: "👤",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "3:4",
    stylePrefix: "Character concept art, full body, detailed design sheet, ",
    styleSuffix: ", expressive, character turnaround, game character design",
    visualTraits: ["concept art", "character design", "expressive", "detailed", "game art"],
  },
  architecture: {
    id: "architecture",
    name: "Architecture",
    description: "Architectural visualizations and building designs",
    icon: "🏛",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Architectural visualization, modernist, clean geometric forms, ",
    styleSuffix: ", architectural photography, dramatic sky, professional render",
    visualTraits: ["architectural", "geometric", "modernist", "clean lines", "professional"],
  },
  "banana-nature": {
    id: "banana-nature",
    name: "Banana Nature",
    description: "Surreal nature scenes with banana-inspired aesthetics",
    icon: "🍌",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Surreal nature, banana aesthetic, tropical vibes, vibrant greens and yellows, ",
    styleSuffix: ", dreamlike landscape, magical realism",
    visualTraits: ["surreal", "tropical", "vibrant", "banana aesthetic", "dreamlike"],
  },
  "comic-book": {
    id: "comic-book",
    name: "Comic Book",
    description: "Comic book art with bold lines and dramatic shading",
    icon: "💥",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "1K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Comic book style, bold outlines, halftone dots, dramatic shading, ",
    styleSuffix: ", comic panel, sequential art, pop art colors, speech bubble style",
    visualTraits: ["comic style", "bold outlines", "halftone", "dramatic", "pop art"],
  },
  cinematic: {
    id: "cinematic",
    name: "Cinematic",
    description: "Movie-quality scenes with dramatic lighting and composition",
    icon: "🎬",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "21:9",
    stylePrefix: "Cinematic shot, anamorphic lens, dramatic lighting, film grade, ",
    styleSuffix: ", movie still, 35mm film, cinematic color grading, depth of field",
    visualTraits: ["cinematic", "dramatic lighting", "movie quality", "film grade", "color graded"],
  },
  steampunk: {
    id: "steampunk",
    name: "Steampunk",
    description: "Victorian-inspired sci-fi with brass and steam aesthetics",
    icon: "⚙",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Steampunk, Victorian era, brass and copper, steam powered, gears, ",
    styleSuffix: ", intricate mechanical details, warm tones, vintage sci-fi",
    visualTraits: ["steampunk", "Victorian", "brass", "mechanical", "vintage sci-fi"],
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "High-tech dystopian future with neon lights and cybernetics",
    icon: "🌃",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Cyberpunk, neon noir, futuristic city, rain slicked streets, holographic ads, ",
    styleSuffix: ", blade runner aesthetic, synthwave colors, dystopian, high contrast",
    visualTraits: ["cyberpunk", "neon", "futuristic", "dystopian", "synthwave"],
  },
  watercolor: {
    id: "watercolor",
    name: "Watercolor",
    description: "Soft watercolor paintings with flowing pigments",
    icon: "🖌",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "4:3",
    stylePrefix: "Watercolor painting, soft washes, flowing pigments, paper texture, ",
    styleSuffix: ", artistic, impressionist style, wet on wet technique, delicate",
    visualTraits: ["watercolor", "soft", "flowing", "artistic", "delicate"],
  },
  anime: {
    id: "anime",
    name: "Anime",
    description: "Japanese anime and manga style artwork",
    icon: "🌸",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "1K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Anime style, Japanese animation, cel shading, vibrant eyes, ",
    styleSuffix: ", manga aesthetic, Studio Ghibli inspired, anime background",
    visualTraits: ["anime", "cel shading", "manga", "vibrant", "japanese style"],
  },
  isometric: {
    id: "isometric",
    name: "Isometric",
    description: "Isometric game-style views with 3/4 perspective",
    icon: "🔷",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "1:1",
    stylePrefix: "Isometric view, 3/4 perspective, diagonal grid, axonometric, ",
    styleSuffix: ", game asset style, clean geometric, flat design with depth",
    visualTraits: ["isometric", "3/4 perspective", "geometric", "game style", "axonometric"],
  },
  "technical-drawing": {
    id: "technical-drawing",
    name: "Technical Drawing",
    description: "Engineering-style technical illustrations and blueprints",
    icon: "📐",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "4:3",
    stylePrefix: "Technical drawing, blueprint style, engineering diagram, precise lines, ",
    styleSuffix: ", monochrome, white on blue, architectural plan, labeled",
    visualTraits: ["technical", "blueprint", "precise lines", "engineering", "diagram"],
  },
  fantasy: {
    id: "fantasy",
    name: "Fantasy",
    description: "Epic fantasy scenes with magic, mythical creatures, and ancient worlds",
    icon: "🐉",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "16:9",
    stylePrefix: "Epic fantasy, magical atmosphere, mythical, ancient world, ",
    styleSuffix: ", Dungeons and Dragons style, ethereal lighting, grand scale",
    visualTraits: ["fantasy", "magical", "mythical", "epic", "ethereal"],
  },
  map: {
    id: "map",
    name: "Map",
    description: "Fantasy and geographic maps with cartographic styling",
    icon: "🗺",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "4:3",
    stylePrefix: "Fantasy map, cartographic style, parchment texture, topographic, ",
    styleSuffix: ", hand-drawn islands, compass rose, sea monsters, old map aesthetic",
    visualTraits: ["map", "cartographic", "parchment", "topographic", "hand-drawn"],
  },
  "macro-food": {
    id: "macro-food",
    name: "Macro Food",
    description: "Close-up food photography with mouth-watering details",
    icon: "🍕",
    recommendedModel: "gemini-3.1-flash-image-preview",
    defaultResolution: "2K",
    defaultAspectRatio: "1:1",
    stylePrefix: "Macro food photography, mouth-watering, steam rising, ",
    styleSuffix: ", shallow depth of field, food styling, culinary art, appetizing",
    visualTraits: ["macro", "food", "mouth-watering", "culinary", "appetizing"],
  },
};

export function getDomainMode(id: DomainMode): DomainModeConfig {
  return DOMAIN_MODES[id];
}

export function listDomainModes(): DomainModeConfig[] {
  return DOMAIN_MODE_VALUES.map((id) => DOMAIN_MODES[id]);
}

export function resolveDomainConfig(
  mode?: DomainMode,
): DomainModeConfig | null {
  if (!mode) return null;
  return DOMAIN_MODES[mode] || null;
}
